# Generated by Django 4.2.5 on 2024-06-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не більше 20 символів', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='не більше 15 символів', max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('kid_age', models.CharField(max_length=50, null=True, verbose_name='Вік учня')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='Вартість')),
                ('date_price', models.IntegerField(null=True, verbose_name='Дата_ціна')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Опис')),
                ('category', models.ForeignKey(help_text='оберіть категорію', null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_1.category', verbose_name='категорія курсу')),
            ],
        ),
    ]
